- name: 是否有旧版本
  command: docker version
  register: result
  ignore_errors: True

- name: 清除旧版
  tags: uninstall
  yum: name={{ item }}  state=absent
  items:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine
  when: result is succeeded 

- name: 安装 yum-utils
  yum: name={{ item }} state=present
  items:
  - yum-utils

- name: 加入 docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"  

- name: 安装docker
  yum: name=docker-ce state=present

- name: 启动服务
  service: name=docker state=started enabled=true
